//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_staircase {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceHintsRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceHintsRu() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_staircase.ResourceHintsRu", typeof(ResourceHintsRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать слой.
        /// </summary>
        internal static string CrossCurTextBox {
            get {
                return ResourceManager.GetString("CrossCurTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота самого высокого блока арта (Для арта из 2 слоев - 2 например).
        /// </summary>
        internal static string CrossMaxHeight {
            get {
                return ResourceManager.GetString("CrossMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующий слой.
        /// </summary>
        internal static string CrossNextButton {
            get {
                return ResourceManager.GetString("CrossNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущий слой.
        /// </summary>
        internal static string CrossPrevButton {
            get {
                return ResourceManager.GetString("CrossPrevButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть на схему арта сбоку (для трехмерных).
        /// </summary>
        internal static string CrossViewButton {
            get {
                return ResourceManager.GetString("CrossViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сгенерировать плосский арт.
        /// </summary>
        internal static string FlatRadio {
            get {
                return ResourceManager.GetString("FlatRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сгенерировать трехмерный арт.
        /// </summary>
        internal static string FullRadio {
            get {
                return ResourceManager.GetString("FullRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать процесс создания арта.
        /// </summary>
        internal static string GenerateButton {
            get {
                return ResourceManager.GetString("GenerateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задать высоту изображения.
        /// </summary>
        internal static string HeightTextBox {
            get {
                return ResourceManager.GetString("HeightTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сгенерировать упрощенный трехмерный арт.
        /// </summary>
        internal static string LiteRadio {
            get {
                return ResourceManager.GetString("LiteRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть список материалов.
        /// </summary>
        internal static string MatButton {
            get {
                return ResourceManager.GetString("MatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настроить список используемых материалов.
        /// </summary>
        internal static string MatOptionsButton {
            get {
                return ResourceManager.GetString("MatOptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следует выбрать изображение. Показать дополнительную информацию об ошибке?.
        /// </summary>
        internal static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть новое изображение.
        /// </summary>
        internal static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выгрузить схематик-файл арта.
        /// </summary>
        internal static string SchemButton {
            get {
                return ResourceManager.GetString("SchemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмечено - размер указывается в блоках, Не отмечено - размер указывается в картах.
        /// </summary>
        internal static string SizeCheckBox {
            get {
                return ResourceManager.GetString("SizeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать поверх других окон.
        /// </summary>
        internal static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дважды нажмите на изображения для отображения поверх всех окон (Отключить это сообщение можно в настройках).
        /// </summary>
        internal static string TopTopMostHint {
            get {
                return ResourceManager.GetString("TopTopMostHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть на схему арта сверху (для плоских).
        /// </summary>
        internal static string TopViewButton {
            get {
                return ResourceManager.GetString("TopViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть арт в реальном размере (так он будет выглядеть в игре).
        /// </summary>
        internal static string ViewImgButton {
            get {
                return ResourceManager.GetString("ViewImgButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задать ширину изображения.
        /// </summary>
        internal static string WidthTextBox {
            get {
                return ResourceManager.GetString("WidthTextBox", resourceCulture);
            }
        }
    }
}
