//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_staircase.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_staircase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;ID&quot;:1,&quot;NormalColor&quot;:[109,153,48],&quot;DarkColor&quot;:[89,125,39],&quot;LightColor&quot;:[127,178,56]}
        ///{&quot;ID&quot;:2,&quot;NormalColor&quot;:[213,201,140],&quot;DarkColor&quot;:[174,164,115],&quot;LightColor&quot;:[247,233,163]}
        ///{&quot;ID&quot;:3,&quot;NormalColor&quot;:[171,171,171],&quot;DarkColor&quot;:[140,140,140],&quot;LightColor&quot;:[199,199,199]}
        ///{&quot;ID&quot;:4,&quot;NormalColor&quot;:[220,0,0],&quot;DarkColor&quot;:[180,0,0],&quot;LightColor&quot;:[255,0,0]}
        ///{&quot;ID&quot;:5,&quot;NormalColor&quot;:[138,138,220],&quot;DarkColor&quot;:[112,112,180],&quot;LightColor&quot;:[160,160,255]}
        ///{&quot;ID&quot;:6,&quot;NormalColor&quot;:[144,144,144],&quot;DarkColor&quot;:[117,117,117],&quot;LightColor [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ColorsIDS {
            get {
                return ResourceManager.GetString("ColorsIDS", resourceCulture);
            }
        }
    }
}
