//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_staircase.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_staircase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-127-178-56
        ///2-247-233-163
        ///3-199-199-199
        ///4-255-0-0
        ///5-160-160-255
        ///6-167-167-167
        ///7-0-124-0
        ///8-255-255-255
        ///9-164-168-184
        ///10-151-109-77
        ///11-112-112-112
        ///12-64-64-255
        ///13-143-119-72
        ///14-255-252-245
        ///15-216-127-51
        ///16-178-76-216
        ///17-102-153-216
        ///18-229-229-51
        ///19-127-204-25
        ///20-242-127-165
        ///21-76-76-76
        ///22-153-153-153
        ///23-76-127-153
        ///24-127-63-178
        ///25-51-76-178
        ///26-102-76-51
        ///27-102-127-51
        ///28-153-51-51
        ///29-25-25-25
        ///30-250-238-77
        ///31-92-219-213
        ///32-74-128-255
        ///33-0-217-58
        ///34-129-86-49
        ///35-112-2-0
        ///36-20 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ColorsIDS {
            get {
                return ResourceManager.GetString("ColorsIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HelpSelectingMaterialsEn {
            get {
                object obj = ResourceManager.GetObject("HelpSelectingMaterialsEn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HelpSelectingMaterialsRu {
            get {
                object obj = ResourceManager.GetObject("HelpSelectingMaterialsRu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap North {
            get {
                object obj = ResourceManager.GetObject("North", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] textures {
            get {
                object obj = ResourceManager.GetObject("textures", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
