//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_staircase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True~grass_side.png-Grass block-2-0-False,slime.png-Slimeblock-165-0-True~grass_s" +
            "ide.png-Grass block-2-0-False\r\nTrue~sandstone_bottom.png-Sandstone-24-0-False,sa" +
            "nd.png-Sand-12-0-False,planks_birch.png-Birch planks-5-2-False,end_stone.png-End" +
            " stone-121-0-False,sandstone_carved.png-Chiseled sandstone-24-1-False,sandstone_" +
            "smooth.png-Smooth sandstone-24-2-False,bone_block_top.png-Bone block-216-0-False" +
            ",glowstone.png-Glowstone-89-0-False,end_bricks.png-Endstone bricks-206-0-False~s" +
            "andstone_bottom.png-Sandstone-24-0-False\r\nTrue~web.png-Web-30-0-False~web.png-We" +
            "b-30-0-False\r\nTrue~redstone_block.png-Redstone block-152-0-False,tnt_side.png-TN" +
            "T-46-0-False~redstone_block.png-Redstone block-152-0-False\r\nTrue~ice_packed.png-" +
            "Packed ice-174-0-False,frosted_ice_0.png-Frosted ice-212-0-False,ice.png-Ice-79-" +
            "0-False~ice_packed.png-Packed ice-174-0-False\r\nTrue~iron_block.png-Iron block-42" +
            "-0-False,iron_trapdoor.png-Iron trapdoor-167-0-True,iron_bars.png-Iron bars-101-" +
            "0-True,brewing_stand.png-Brewing stand-117-0-True~iron_block.png-Iron block-42-0" +
            "-False\r\nTrue~leaves_oak.png-Oak leaves-18-0-False,wheat_stage_7.png-Wheat-59-7-T" +
            "rue~leaves_oak.png-Oak leaves-18-0-False\r\nTrue~snow.png-Snow block-80-0-False,wo" +
            "ol_colored_white.png-White wool-35-0-False,snow.png-Snow layer-78-0-True,wool_co" +
            "lored_white.png-White carpet-171-0-True,glass_white.png-White stained glass-95-0" +
            "-True,glass_white.png-White stained glass pane-160-0-True,glazed_terracotta_whit" +
            "e.png-White glazed terracota-220-0-True~snow.png-Snow block-80-0-False\r\nTrue~cla" +
            "y.png-Clay-82-0-False~clay.png-Clay-82-0-False\r\nTrue~dirt.png-Dirt-3-0-False,pla" +
            "nks_jungle.png-Jungle planks-5-3-False,coarse_dirt.png-Coarse dirt-3-1-False,juk" +
            "ebox_top.png-Jukebox-84-0-False,stone_granite.png-Granite-1-1-False,stone_granit" +
            "e_smooth.png-Polished granite-1-2-False,grass_path_side.png-Grass path-208-0-Fal" +
            "se~dirt.png-Dirt-3-0-False\r\nTrue~stone.png-Stone-1-0-False,cobblestone.png-Cobbl" +
            "estone-4-0-False,stone_slab_top.png-Stone slab-44-0-False,stonebrick.png-Stone b" +
            "ricks-98-0-False,stonebrick_mossy.png-Mossy stone bricks-98-1-False,stonebrick_c" +
            "racked.png-Cracked stone bricks-98-2-False,stonebrick_carved.png-Chiseled stone " +
            "bricks-98-3-False,cobblestone_mossy.png-Mossy cobblestone-48-0-False,gravel.png-" +
            "Gravel-13-0-False,stone_andesite.png-Andesite-1-5-False,stone_andesite_smooth.pn" +
            "g-Polished andesite-1-6-False,bedrock.png-Bedrock-7-0-False,furnace_front_off.pn" +
            "g-Furnace-61-0-False~stone.png-Stone-1-0-False\r\nTrue~water_overlay.png-Water-9-0" +
            "-False~water_overlay.png-Water-9-0-False\r\nTrue~planks_oak.png-Oak planks-5-0-Fal" +
            "se,crafting_table_front.png-Workbench-58-0-False,bookshelf.png-Bookshelf-47-0-Fa" +
            "lse,noteblock.png-Noteblock-25-0-False~planks_oak.png-Oak planks-5-0-False\r\nTrue" +
            "~stone_diorite.png-Diorite-1-3-False,stone_diorite_smooth.png-Polished diorite-1" +
            "-4-False,quartz_block_bottom.png-Quartz-155-0-False,quartz_block_chiseled.png-Ch" +
            "iseled quartz-155-1-False,quartz_block_lines.png-Quartz pillar-155-2-False,sea_l" +
            "antern.png-Sea latern-169-0-False~stone_diorite.png-Diorite-1-3-False\r\nTrue~wool" +
            "_colored_orange.png-Orange wool-35-1-False,planks_acacia.png-Acacia planks-5-4-F" +
            "alse,wool_colored_orange.png-Orange carpet-171-1-False,pumpkin_face_off.png-Pump" +
            "kin-86-0-False,red_sand.png-Red sand-12-1-False,red_sandstone_normal.png-Red san" +
            "dstone-179-0-False,red_sandstone_carved.png-Chiseled red sandstone-179-1-False,r" +
            "ed_sandstone_smooth.png-Smooth red sandstone-179-2-False,hardened_clay.png-Stain" +
            "ed clay (terracota)-172-0-False,glazed_terracotta_orange.png-Orange glazed terra" +
            "cotta-236-0-False,concrete_orange.png-Orange concrete-251-1-False,concrete_powde" +
            "r_orange.png-Orange concrete powder-252-1-False~wool_colored_orange.png-Orange w" +
            "ool-35-1-False\r\nTrue~purpur_block.png-Purpur block-201-0-False,purpur_pillar.png" +
            "-Purpur pillar-202-0-False,wool_colored_magenta.png-Magenta wool-35-2-False,wool" +
            "_colored_magenta.png-Magenta carpet-171-2-True,glazed_terracotta_magenta.png-Mag" +
            "enta glazed terracotta-237-0-False,concrete_magenta.png-Magenta concrete-251-2-F" +
            "alse,concrete_powder_magenta.png-Magenta concrete powder-252-2-False~purpur_bloc" +
            "k.png-Purpur block-201-0-False\r\nTrue~wool_colored_light_blue.png-Light blue wool" +
            "-35-3-False,wool_colored_light_blue.png-Light blue carpet-171-3-True,glazed_terr" +
            "acotta_light_blue.png-Light blue glazed terracotta-238-0-False,concrete_light_bl" +
            "ue.png-Light blue concrete-251-3-False,concrete_powder_light_blue.png-Light blue" +
            " concrete powder-252-3-False~wool_colored_light_blue.png-Light blue wool-35-3-Fa" +
            "lse\r\nTrue~wool_colored_yellow.png-Yellow wool-35-4-False,wool_colored_yellow.png" +
            "-Yellow carpet-171-4-True,glazed_terracotta_yellow.png-Yellow glazed terracotta-" +
            "239-0-False,concrete_yellow.png-Yellow concrete-251-4-False,concrete_powder_yell" +
            "ow.png-Yellow concrete powder-252-4-False,hay_block_side.png-Hay bale-170-0-Fals" +
            "e,sponge.png-Sponge-19-0-False,sponge_wet.png-Wet sponge-19-1-False~wool_colored" +
            "_yellow.png-Yellow wool-35-4-False\r\nTrue~melon_side.png-Melon-103-0-False,wool_c" +
            "olored_lime.png-Lime wool-35-5-False,wool_colored_lime.png-Lime carpet-171-5-Tru" +
            "e,glazed_terracotta_lime.png-Lime glazed terracotta-240-0-False,concrete_lime.pn" +
            "g-Lime concrete-251-5-False,concrete_powder_lime.png-Lime concrete powder-252-5-" +
            "False~melon_side.png-Melon-103-0-False\r\nTrue~wool_colored_pink.png-Pink wool-35-" +
            "6-False,wool_colored_pink.png-Pink carpet-171-6-True,glazed_terracotta_pink.png-" +
            "Pink glazed terracotta-241-0-False,concrete_pink.png-Pink concrete-251-6-False,c" +
            "oncrete_powder_pink.png-Pink concrete powder-252-6-False~wool_colored_pink.png-P" +
            "ink wool-35-6-False\r\nTrue~wool_colored_gray.png-Gray wool-35-7-False,wool_colore" +
            "d_gray.png-Gray carpet-171-7-True,glazed_terracotta_gray.png-Gray glazed terraco" +
            "tta-242-0-False,concrete_gray.png-Gray concrete-251-7-False,concrete_powder_gray" +
            ".png-Gray concrete powder-252-7-False~wool_colored_gray.png-Gray wool-35-7-False" +
            "\r\nTrue~wool_colored_silver.png-Light gray wool-35-8-False,wool_colored_silver.pn" +
            "g-Light gray carpet-171-8-True,glazed_terracotta_silver.png-Light gray glazed te" +
            "rracotta-243-0-False,concrete_silver.png-Light gray concrete-251-8-False,concret" +
            "e_powder_silver.png-Light gray concrete powder-252-8-False~wool_colored_silver.p" +
            "ng-Light gray wool-35-8-False\r\nTrue~wool_colored_cyan.png-Cyan wool-35-9-False,w" +
            "ool_colored_cyan.png-Cyan carpet-171-9-True,glazed_terracotta_cyan.png-Cyan glaz" +
            "ed terracotta-244-0-False,concrete_cyan.png-Cyan concrete-251-9-False,concrete_p" +
            "owder_cyan.png-Cyan concrete powder-252-9-False,prismarine_rough.png-Prismarine-" +
            "168-0-False~wool_colored_cyan.png-Cyan wool-35-9-False\r\nTrue~wool_colored_purple" +
            ".png-Purple wool-35-10-False,wool_colored_purple.png-Purple carpet-171-10-True,g" +
            "lazed_terracotta_purple.png-Purple glazed terracotta-245-0-False,concrete_purple" +
            ".png-Purple concrete-251-10-False,concrete_powder_purple.png-Purple concrete pow" +
            "der-252-10-False,mycelium_side.png-Mycelium-110-0-False~wool_colored_purple.png-" +
            "Purple wool-35-10-False\r\nTrue~wool_colored_blue.png-Blue wool-35-11-False,wool_c" +
            "olored_blue.png-Blue carpet-171-11-True,glazed_terracotta_blue.png-Blue glazed t" +
            "erracotta-246-0-False,concrete_blue.png-Blue concrete-251-11-False,concrete_powd" +
            "er_blue.png-Blue concrete powder-252-11-False~wool_colored_blue.png-Blue wool-35" +
            "-11-False\r\nTrue~soul_sand.png-Soulsand-88-0-False,planks_big_oak.png-Dark oak pl" +
            "anks-5-5-False,wool_colored_brown.png-Brown wool-35-12-False,wool_colored_brown." +
            "png-Brown carpet-171-12-True,glazed_terracotta_brown.png-Brown glazed terracotta" +
            "-247-0-False,concrete_brown.png-Brown concrete-251-12-False,concrete_powder_brow" +
            "n.png-Brown concrete powder-252-12-False~soul_sand.png-Soulsand-88-0-False\r\nTrue" +
            "~wool_colored_green.png-Green wool-35-13-False,wool_colored_green.png-Green carp" +
            "et-171-13-True,glazed_terracotta_green.png-Green glazed terracotta-248-0-False,c" +
            "oncrete_green.png-Green concrete-251-13-False,concrete_powder_green.png-Green co" +
            "ncrete powder-252-13-False~wool_colored_green.png-Green wool-35-13-False\r\nTrue~w" +
            "ool_colored_red.png-Red wool-35-14-False,wool_colored_red.png-Red carpet-171-14-" +
            "True,glazed_terracotta_red.png-Red glazed terracotta-249-0-False,concrete_red.pn" +
            "g-Red concrete-251-14-False,concrete_powder_red.png-Red concrete powder-252-14-F" +
            "alse,brick.png-Bricks-45-0-False,nether_wart_block.png-Nether wart block-214-0-F" +
            "alse~wool_colored_red.png-Red wool-35-14-False\r\nTrue~wool_colored_black.png-Blac" +
            "k wool-35-15-False,wool_colored_black.png-Black carpet-171-15-True,glazed_terrac" +
            "otta_black.png-Black glazed terracotta-250-0-False,concrete_black.png-Black conc" +
            "rete-251-15-False,concrete_powder_black.png-Black concrete powder-252-15-False,c" +
            "oal_block.png-Block of coal-173-0-False,obsidian.png-Obsidian-49-0-False~wool_co" +
            "lored_black.png-Black wool-35-15-False\r\nTrue~gold_block.png-Gold block-41-0-Fals" +
            "e,gold_block.png-Gold pressure plate-147-0-True~gold_block.png-Gold block-41-0-F" +
            "alse\r\nTrue~prismarine_bricks.png-Prismarine bricks-168-1-False,prismarine_dark.p" +
            "ng-Dark prismarine-168-2-False,diamond_block.png-Diamond block-57-0-False,beacon" +
            ".png-Beacon-138-0-True~prismarine_bricks.png-Prismarine bricks-168-1-False\r\nTrue" +
            "~lapis_block.png-Lapiz lazuli block-22-0-False~lapis_block.png-Lapiz lazuli bloc" +
            "k-22-0-False\r\nTrue~emerald_block.png-Emerald block-133-0-False~emerald_block.png" +
            "-Emerald block-133-0-False\r\nTrue~planks_spruce.png-Spruce planks-5-1-False,dirt_" +
            "podzol_side.png-Podzol-3-2-False~planks_spruce.png-Spruce planks-5-1-False\r\nTrue" +
            "~netherrack.png-Netherrack-87-0-False,nether_brick.png-Nether bricks-112-0-False" +
            ",red_nether_brick.png-Red nether bricks-215-0-False,magma.png-Magma block-213-0-" +
            "False~netherrack.png-Netherrack-87-0-False\r\nTrue~hardened_clay_stained_white.png" +
            "-White terracota-159-0-False~hardened_clay_stained_white.png-White terracota-159" +
            "-0-False\r\nTrue~hardened_clay_stained_orange.png-Orange terracota-159-1-False~har" +
            "dened_clay_stained_orange.png-Orange terracota-159-1-False\r\nTrue~hardened_clay_s" +
            "tained_magenta.png-Magenta terracota-159-2-False~hardened_clay_stained_magenta.p" +
            "ng-Magenta terracota-159-2-False\r\nTrue~hardened_clay_stained_light_blue.png-Ligh" +
            "t blue terracota-159-3-False~hardened_clay_stained_light_blue.png-Light blue ter" +
            "racota-159-3-False\r\nTrue~hardened_clay_stained_yellow.png-Yellow terracota-159-4" +
            "-False~hardened_clay_stained_yellow.png-Yellow terracota-159-4-False\r\nTrue~harde" +
            "ned_clay_stained_lime.png-Lime terracota-159-5-False~hardened_clay_stained_lime." +
            "png-Lime terracota-159-5-False\r\nTrue~hardened_clay_stained_pink.png-Pink terraco" +
            "ta-159-6-False~hardened_clay_stained_pink.png-Pink terracota-159-6-False\r\nTrue~h" +
            "ardened_clay_stained_gray.png-Gray terracota-159-7-False~hardened_clay_stained_g" +
            "ray.png-Gray terracota-159-7-False\r\nTrue~hardened_clay_stained_silver.png-Light " +
            "gray terracota-159-8-False~hardened_clay_stained_silver.png-Light gray terracota" +
            "-159-8-False\r\nTrue~hardened_clay_stained_cyan.png-Cyan terracota-159-9-False~har" +
            "dened_clay_stained_cyan.png-Cyan terracota-159-9-False\r\nTrue~hardened_clay_stain" +
            "ed_purple.png-Purple terracota-159-10-False~hardened_clay_stained_purple.png-Pur" +
            "ple terracota-159-10-False\r\nTrue~hardened_clay_stained_blue.png-Blue terracota-1" +
            "59-11-False~hardened_clay_stained_blue.png-Blue terracota-159-11-False\r\nTrue~har" +
            "dened_clay_stained_brown.png-Brown terracota-159-12-False~hardened_clay_stained_" +
            "brown.png-Brown terracota-159-12-False\r\nTrue~hardened_clay_stained_green.png-Gre" +
            "en terracota-159-13-False~hardened_clay_stained_green.png-Green terracota-159-13" +
            "-False\r\nTrue~hardened_clay_stained_red.png-Red terracota-159-14-False~hardened_c" +
            "lay_stained_red.png-Red terracota-159-14-False\r\nTrue~hardened_clay_stained_black" +
            ".png-Black terracota-159-15-False~hardened_clay_stained_black.png-Black terracot" +
            "a-159-15-False")]
        public string PossibleBlocks {
            get {
                return ((string)(this["PossibleBlocks"]));
            }
            set {
                this["PossibleBlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideTips {
            get {
                return ((bool)(this["HideTips"]));
            }
            set {
                this["HideTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte ConvertingMethod {
            get {
                return ((byte)(this["ConvertingMethod"]));
            }
            set {
                this["ConvertingMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte GeneratingMethod {
            get {
                return ((byte)(this["GeneratingMethod"]));
            }
            set {
                this["GeneratingMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color defMeshColor {
            get {
                return ((global::System.Drawing.Color)(this["defMeshColor"]));
            }
            set {
                this["defMeshColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color chunkMeshColor {
            get {
                return ((global::System.Drawing.Color)(this["chunkMeshColor"]));
            }
            set {
                this["chunkMeshColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color mapMeshColor {
            get {
                return ((global::System.Drawing.Color)(this["mapMeshColor"]));
            }
            set {
                this["mapMeshColor"] = value;
            }
        }
    }
}
